# Generated by Django 2.2.7 on 2019-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturlmodel',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
