# Generated by Django 2.2.7 on 2019-11-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20191124_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturlmodel',
            old_name='hash_code',
            new_name='hash_value',
        ),
    ]
